version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "555"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "555"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: {}
